# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwarpal" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "1a66568dc1eb48167a1fd868593dcad6de837856028ed81b618d1174b2626cf9"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "41ddf686b15352e7f666e87a874fbe18ac5b63445d382a559cfd25ed607f5263"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "389f101fa9a27b4b6a0aaa945951d2c5c73af33251bab513e61bb16e9f2d28c4"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a9d75a1b7998e4e826eb9d6120dea173305c76ebcf59588fce16cc93d1cf1185"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwarpal"
  desc "A quality firewall between AI coding agents and your repository"
  homepage "https://github.com/YellowFoxH4XOR/dwarpal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwarpal"

  # No zap stanza required

end
