# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwarpal" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "0955e71bfb41efdb8c85abc144617004e231e1ac01593819f3b62ffca15e71ca"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5544dbcb489c0ef2d0eb7c1539cc78ad6fa03033aee1b5792a62e47613d69d8"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f48b2e2c002f6ec44a97c10a05cf27fc9f7746daf8231cd7a2dc5651139b4d2b"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e42b6e186c09776ca1c9ea878ee1ba242ded8bd3c494d40d93a2f1b36ada351"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwarpal"
  desc "A quality firewall between AI coding agents and your repository"
  homepage "https://github.com/YellowFoxH4XOR/dwarpal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwarpal"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dwarpal"]
    end
  end

  # No zap stanza required

end
