# This file was generated by GoReleaser. DO NOT EDIT.
cask "dwarpal" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b73b277ec0590aeee4e7fbed5a8734c8d1eda0dba079cbd7f548ceb4153e414e"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35014c4b2343fe2fa144465a6c0a6d8e7c4c4e37ee32d5a518272d65bc4acd0e"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fafcc3af450f81c4bf269c534240a352a73e31daec2e6b86844ab1bb229b9979"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b794fcc839d9d8efebe92a93ff9fd14dd4621bf87407b7b6be301eae01d8be1f"
      url "https://github.com/YellowFoxH4XOR/dwarpal/releases/download/v#{version}/dwarpal_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dwarpal"
  desc "A quality firewall between AI coding agents and your repository"
  homepage "https://github.com/YellowFoxH4XOR/dwarpal"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dwarpal"

  # No zap stanza required

end
